language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
env:
  global:
  - ENCRYPTION_LABEL: "ed20e672ae2c"
  - COMMIT_AUTHOR_EMAIL: "RRMoelker@users.noreply.github.com"
script: bash ./scripts/deploy.sh
